apiVersion: topo.yndd.io/v1alpha1
kind: Template
metadata:
  name: ss-tmpl1
  namespace: default
spec:
  properties:
    network:
      networkInstanceName: mgmt
      addressingScheme: dual-stack
      prefixes: [10.0.0.0/16, 2000::/56]
      ntpServers: [1.2.3.4, 2.3.4.5]
      dnsServers: [8.8.8.8, 8.8.4.4]
    fabric:
      settings:
        maxUplinksTier2ToTier1: 4
        maxUplinksTier3ToTier2: 4
      tier1:
        num: 2
        vendorInfo:
        - vendorType: nokiaSRL
          platform: "IXR-D3"
      pod:
      - num: 1
        tier3:
          num: 4
          uplinkPerNode: 2
          vendorInfo:
          - vendorType: nokiaSRL
            platform: "IXR-D3"
        tier2:
          num: 2
          uplinkPerNode: 4
          vendorInfo:
          - vendorType: nokiaSRL
            platform: "IXR-D3"
